name: receipt_reader
description: "A Flutter package for reading and processing receipts using Google ML Kit."
version: 0.0.1
homepage: # Consider adding your project's GitHub repo or website.

environment:
  sdk: '>=3.5.3 <4.0.0' # Use a more specific range to prevent future breaking changes.
  flutter: ">=2.5.0 <4.0.0" # Updated to a more recent minimum Flutter version.

dependencies:
  flutter:
    sdk: flutter

  # Camera package for capturing receipt images.
  camera: ^0.11.0+2
  
  # ML Kit for recognizing text from receipts.
  google_mlkit_text_recognition: ^0.14.0

  # Image picker for selecting receipt images from the gallery or camera.
  image_picker: ^1.1.2
  
  # Path provider for storing and retrieving receipt images from the local filesystem.
  path_provider: ^2.1.4
  
  # Google Generative AI (if needed for advanced processing; otherwise, remove this if not used).
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Flutter's lints package for code quality and linting.
  flutter_lints: ^4.0.0
  
  # Mockito for creating mock objects in unit tests.
  mockito: ^5.4.4
  
  # Build runner for code generation when using mockito and other code-generating packages.
  build_runner: ^2.4.13

# Assets: Add test assets like images for testing purposes.
flutter:
  assets:
    - test/assets/receipt.jpg # Add your test receipt image for widget tests.

# Fonts: If you want to include custom fonts, uncomment and configure as necessary.
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
